name: Publish to WinGet

on:
  release:
    types: [released]
  workflow_dispatch:

defaults:
run:
  shell: pwsh

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - name: Extract version from release tag
        id: extract_version
        run: |
          $version=${{ github.event.release.tag_name }}.Trim("v")
          $pkgIdentifier=$version.Contains("-") ? "Microsoft.PowerShell.Preview" : "Microsoft.PowerShell"
          echo "version=$version" >> $GITHUB_OUTPUT
      - uses: vedantmgoyal2009/winget-releaser@1d370507249956659e4ec675a221bd2d0f3fe561
        with:
          identifier: ${{ steps.extract_version.outputs.pkgIdentifier }} 
          version: ${{ steps.extract_version.outputs.version }}
          token: ${{ secrets.WINGET_TOKEN }}
          fork-user: pwshBot
